<script>
  import FormField from "../components/FormField.svelte";
  import RenderCard from "../components/RenderCard.svelte";
  import Loader from "../components/Loader.svelte";
  import "../app.css";
  import { onMount, afterUpdate } from "svelte";

  let searchText = "";
  let loading = false;
  let searchResult = null;
  let allPosts = [];
  let searchTimeout = null;
  const fetchPosts = async () => {
    loading = true;

    try {
      const response = await fetch("http://localhost:8080/api/v1/post", {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      });

      if (response.ok) {
        const result = await response.json();
        allPosts = result.data.reverse();
      }
    } catch (err) {
      alert(err);
    } finally {
      loading = false;
    }
  };

  onMount(() => {
    fetchPosts();
  });

  afterUpdate(() => {
    handleSearchChange();
  });

  const handleSearchChange = () => {
    clearTimeout(searchTimeout);
    searchTimeout = setTimeout(() => {
      const searchedResult = allPosts.filter(
        (item) =>
          item.name.toLowerCase().includes(searchText.toLowerCase()) ||
          item.prompt.toLowerCase().includes(searchText.toLowerCase())
      );
      searchResult = searchedResult;
    }, 500);
  };
</script>

<section class="max-w-7xl mx-auto">
  <div>
    <h1 class="font-extrabold text-[#222328] text-[32px]">
      The Community Showcase
    </h1>
    <p class="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
      Browse through a collection? of imaginative and visually stunning images
      generated by DALL-E AI
    </p>
  </div>

  <div class="mt-16">
    <FormField
      labelName="Search posts"
      name="text"
      placeholder="Search something..."
      bind:value={searchText}
    />
  </div>

  <div class="mt-10">
    <div
      class="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3"
    />
  </div>

  <div
    class="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3 mb-6"
  >
    {#if loading}
      <Loader />
    {:else if searchResult}
      {#each searchResult as post}
        <RenderCard {...post} />
      {/each}
    {:else if !searchResult && !loading}
      {#each allPosts as post}
        <RenderCard {...post} />
      {:else}
        <h2>No posts</h2>
      {/each}
    {/if}
  </div>
</section>
